// TODAY IN HISTORY SCREEN
export const FETCH_FACTS = 'FETCH_FACTS';
export const CHANGE_DATE = 'CHANGE_DATE';
export const FETCH_FACT_BOOKS = 'FETCH_FACT_BOOKS';
export const FETCH_FACT_VIDEOS = 'FETCH_FACT_VIDEOS';

// AUTHENTICATION
export const FB_LOGIN_FULFILLED = 'FB_LOGIN_FULFILLED';
export const FB_LOGIN_REJECTED = 'FB_LOGIN_REJECTED';