// TODAY IN HISTORY
export const FETCH_FACTS = 'FETCH_FACTS';
export const FETCH_NEWS= 'FETCH_NEWS';
export const CHANGE_DATE = 'CHANGE_DATE';
export const CHANGE_FACTS_FILTER = 'CHANGE_FACTS_FILTER';

// FACT DETAILS
export const FETCH_FACT_BOOKS = 'FETCH_FACT_BOOKS';
export const FETCH_FACT_VIDEOS = 'FETCH_FACT_VIDEOS';
export const FETCH_TIMELINE_FACTS = 'FETCH_TIMELINE_FACTS';
export const CHANGE_TIMELINE_RANGE = 'CHANGE_TIMELINE_RANGE';
export const CHANGE_TIMELINE_FILTER = 'CHANGE_TIMELINE_FILTER';

// AUTHENTICATION
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const FB_LOGIN_FULFILLED = 'FB_LOGIN_FULFILLED';
export const FB_LOGIN_REJECTED = 'FB_LOGIN_REJECTED';
export const LOG_OUT = 'LOG_OUT';

// FAVORITE
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const FETCH_FAVORITE = 'FETCH_FAVORITE';
export const CHANGE_FAVORITES_FILTER = 'CHANGE_FAVORITES_FILTER';

// MODAL - COMPONENT
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// COMMON
export const COPY_TO_CLIPBOARD = 'COPY_TO_CLIPBOARD';