// TODAY IN HISTORY
export const FETCH_FACTS = 'FETCH_FACTS';
export const FETCH_FACT_BOOKS = 'FETCH_FACT_BOOKS';
export const FETCH_FACT_VIDEOS = 'FETCH_FACT_VIDEOS';
export const FETCH_NEWS= 'FETCH_NEWS';
export const CHANGE_DATE = 'CHANGE_DATE';

// AUTHENTICATION
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const FB_LOGIN_FULFILLED = 'FB_LOGIN_FULFILLED';
export const FB_LOGIN_REJECTED = 'FB_LOGIN_REJECTED';
export const LOG_OUT = 'LOG_OUT';

// FAVORITE
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const FETCH_FAVORITE = 'FETCH_FAVORITE';